### ISSUE TITLE
Accessing Phytozome vista_rest adapter encounters SSLError

### ISSUE THREAD

**Issue by vivekkrish** [Arabidopsis-Information-Portal/adama#99] opened 2016-01-15 21:56 UTC
We are now utilizing Phytozome JBrowse vista_rest endpoint to power the VISTA conservation tracks in our Araport JBrowse. [Example](https://apps.araport.org/jbrowse/?data=arabidopsis&loc=Chr1:8146351..8150178&tracks=TAIR10_genome,Araport11_Loci,Araport11_gene_models,Vista_Alyrata)

We access their endpoint via an Araport passthrough adapter, which is defined by this [metadata.yml](https://github.com/Arabidopsis-Information-Portal/phytozome_webservices/blob/master/services/vista_rest/metadata.yml).

Here is an example API call:
```
$ curl -v -H "Authorization: Bearer $TOKEN" "https://api.araport.org/community/v0.3/phytozome/vista_rest_v0.2/access/features/Chr1?start=23058437&end=23059296&vista_base_id=611&target_id=962&target_run=660"
```

The passthrough adapter makes a request to Phytozome, before which the request URL is transformed into https://phytozome.jgi.doe.gov/jbrowse/vista_rest/features/Chr1?start=23058437&end=23059296&vista_base_id=611&target_id=962&target_run=660

A successful request to the above URL should return valid JSON back to our JBrowse.

Right around the time of PAG, all Phytozome services have now started using secure HTTP (https).
However, since the change, we have started seeing the following SSLError:
```
{
  "exception": "SSLError",
  "message": "hostname 'phytozome.jgi.doe.gov' doesn't match either of '*.nersc.gov', 'nersc.gov'",
  "status": "error",
  "worker_trace": null
}
```
By default, we leave SSL certificate verification turned on.

The above error is produced by the python requests module, when the SSL certificate verification failed to match the certificate the server responds with, to the hostname (http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors)

I have sent a request to the Phytozome team, asking them to check if the wildcard certificate installed on their server matches the hostname of their application.

In the meanwhile, could we implement a flag in ADAMA, triggered via an entry in `metadata.yml`, which can be used to **turn of*f* certificate verification. Something like:
```
---

name: vista_rest
version: 0.2
description: Passthrough adapter for Phytozome JBrowse REST endpoint serving VISTA alignments
type: passthrough
url: https://phytozome.jgi.doe.gov/jbrowse/vista_rest
whitelist:
  - phytozome.jgi.doe.gov

verify_certificate: false
```

Any downsides to having this functionality?

**Comment by waltermoreira** [comment] 2016-01-15 22:06
This can be implemented easily, but would like the input from @mwvaughn first, as the change may have securities repercussions.

**Comment by mwvaughn** [comment] 2016-01-15 22:15
I don’t think we have a choice but to allow it. Legacy service implementations may not be able to be reconfigured to support the best-practices we are attempting to bring to the plant science community.

In this case, I tried using HTTP and also tried using the canonical name phytozometest-lb.nersc.gov
and neither was a viable solution.

Matt

**Comment by vivekkrish** [comment] 2016-01-15 22:45
Thanks, Matt, I think it's best we allow for this flexibility.

Incidentally, since PAG, we've started experiencing issues with a WSO2 adapter we are (still) using in ThaleMine, which points to Phytomine (also served via phytozome.jgi.doe.gov). Unfortunately, since it is WSO2, we are unable to see the errors on the server. The passthrough URL is https://api.araport.org/data/phytozome_intermine/v1.0.1.

We couldn't use ADAMA since the InterMine imtables infrastructure didn't support sending custom request headers. Josh (from the InterMine team) has recently fixed this issue per our request. So I'm hoping to replace the WSO2 URL with an ADAMA URL.

**Comment by vivekkrish** [comment] 2016-01-15 23:51
Something weird is happening inside the ADAMA passthrough adapter. Sending a request directly to Phytozome's URL doesn't encounter a certificate issue:
```
$ python
Python 2.7.11 (default, Dec 14 2015, 14:29:11) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://phytozome.jgi.doe.gov/jbrowse/vista_rest/features/Chr1?start=23058437&end=23059296&vista_base_id=611&target_id=962&target_run=660')
<Response [200]>
```

**Comment by mwvaughn** [comment] 2016-01-15 23:55
Not necessarily weird. The implementation of cert validation, as well as its stringency, varies between variants of libcurl and Python requests.

On Jan 15, 2016, at 5:52 PM, Vivek Krishnakumar <notifications@github.com<mailto:notifications@github.com>> wrote:


Something weird is happening inside the ADAMA passthrough adapter. Sending a request directly to Phytozome's URL doesn't encounter a certificate issue:

$ python
Python 2.7.11 (default, Dec 14 2015, 14:29:11)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://phytozome.jgi.doe.gov/jbrowse/vista_rest/features/Chr1?start=23058437&end=23059296&vista_base_id=611&target_id=962&target_run=660')
<Response [200]>


-

**Comment by vivekkrish** [comment] 2016-01-16 00:02
Agreed! Definitely need further investigation to figure out what may be happening.

sslshopper.com reports that certs are installed correctly (https://www.sslshopper.com/ssl-checker.html#hostname=phytozome.jgi.doe.gov).

Copy-pasting verbose from Python requests faq page (http://docs.python-requests.org/en/latest/community/faq/#what-are-hostname-doesn-t-match-errors):
>These errors occur when SSL certificate verification fails to match the certificate the server responds with to the hostname Requests thinks it’s contacting. If you’re certain the server’s SSL setup is correct (for example, because you can visit the site with your browser) and you’re using Python 2.6 or 2.7, a possible explanation is that you need Server-Name-Indication.

>Server-Name-Indication, or SNI, is an official extension to SSL where the client tells the server what hostname it is contacting. This is important when servers are using Virtual Hosting. When such servers are hosting more than one SSL site they need to be able to return the appropriate certificate based on the hostname the client is connecting to.

>Python3 and Python 2.7.9+ include native support for SNI in their SSL modules.

My tests are from a Mac OSX running Python 2.7.11, and my assumption then is that its SSL module has SNI support.

**Comment by waltermoreira** [comment] 2016-01-19 21:54
As @vivekkrish pointed, the problem is with the `requests` library.  This issue got fixed by:

- Installing extra crypto libraries: `libffi-dev`, `libssl-dev`
- Install `requests[security]`, instead of just `requests`.

Ansible playbook is updated accordingly.

**Closed by waltermoreira** 2016-01-19 21:54 UTC
Labels: bug, help wanted
